name: Deploy Streamlit Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run syntax check
      run: python -m py_compile dashboard/app.py

    - name: Run streamlit check
      run: streamlit hello --help

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit Cloud
      env:
        ST_EMAIL: ${{ secrets.STREAMLIT_EMAIL }}
        ST_PASSWORD: ${{ secrets.STREAMLIT_PASSWORD }}
      run: |
        echo "Manual deployment required. Run: streamlit deploy"
